Make sure locked tickets cannot be listed
BurntFinance/cw-nfts pull request #3
Opened 2022-08-16 13:52 UTC by Peartes

# Feature

This PR addresses this [issue](https://burnt.atlassian.net/jira/software/c/projects/DAPP/boards/3?modal=detail&selectedIssue=DAPP-234&assignee=6222564659c0740069d919f2)

2022-08-17 14:00 UTC, Peartes commented on contracts/cw721-sellable/src/error.rs
> +    TicketLocked,
Change locked and redeemed error enum to a clearer word

2022-08-17 15:00 UTC, bigs requested changes
Fantastic job. Just one tiny change.

2022-08-18 11:37 UTC, Peartes commented on contracts/cw721-sellable/src/execute.rs
> +        let metadata = info.extension.ok_or(ContractError::NoMetadataPresent)?;
THANKS 😊 🙏

2022-08-18 15:05 UTC, bigs approved these changes

2022-08-18 15:05 UTC, merged